---
title: "p8105_mtp_jc5929"
output: html_document
date: "2022-10-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library(tidyverse)
library(dplyr)
library(knitr)
library(readxl)
library(ggridges)
library(patchwork)

**Cleaning data set**
```{r}
dog_data= read_excel("data/dogweights_07may2022.xlsx",skip = 1,col_types = 
                   c("date", "guess", "guess", "guess", "guess", "text")) %>% 
  janitor::clean_names() %>%
  drop_na(date) %>% 
  subset(raisin != "NA" | simone != "NA" | gagne != "NA") %>%
  select(-x6) %>% 
  separate(date,into=c("year","month","day"),sep="-") %>% 
  separate(raisin,into=c("lbs","oz"),sep=2)%>%
  mutate(lbs=as.numeric(lbs), oz=as.numeric(oz)) %>%
  mutate(raisin=round((lbs+oz/16),2))%>%
  select(-lbs,-oz) %>%
  separate(simone, into=c("lbs","oz"),sep=2) %>%
  mutate(lbs=as.numeric(lbs), oz=as.numeric(oz)) %>%
  mutate(simone=round((lbs+oz/16),2))%>%
  select(-lbs,-oz) %>%
  separate(gagne, into=c("lbs","oz"),sep=2) %>%
  mutate(lbs=as.numeric(lbs), oz=as.numeric(oz)) %>%
  mutate(gagne=round((lbs+oz/16),2)) %>%
  select(-lbs,-oz) %>% 
  separate(std, into=c("lbs","oz"),sep=2) %>%
  mutate(lbs=as.numeric(lbs), oz=as.numeric(oz)) %>%
  mutate(std=round((lbs+oz/16),2)) %>%
  select(-lbs,-oz) %>% 
  pivot_longer(
    raisin:gagne,
    names_to = "dog_name",
    values_to = "weight"
  )                  %>%
  drop_na(weight) %>%
  relocate(std,.after=weight)

```

**Creating a dataframe with notes**
```{r}
notes_df= read_excel("data/dogweights_07may2022.xlsx", skip = 1, col_types = 
                    c("date", "guess", "guess", "guess", "guess", "text")) %>% 
  janitor::clean_names() %>% 
  mutate(notes = x6) %>%
  drop_na(notes) %>%
  select(date,notes) %>%
  select(date, notes) %>% 
  separate(date, into=c("year", "month", "day"),sep="-")
  
```

**Export data sets**
```{r}
write_csv(dog_data, "data/dog.csv")
write_csv(notes_df, "data/notes.csv")
```

*Summary of the data set**
```{r}
 dog_data%>%
   distinct(year,month,day)
```

```{r}
dog_data%>%
  group_by(dog_name) %>%
  summarize(obs=n(),
            avg_weight=mean(weight),
            sd_weight=sd(weight)) %>%
knitr::kable()
```

**Visualization**

```{r}
plot1=dog_data %>%
  group_by(dog_name,weight) %>%
  summarize(count=n()) %>%
  ggplot(aes(x=weight,y=dog_name,fill=dog_name))+
  geom_density_ridges(
    aes(point_color = dog_name, point_shape = dog_name,point_fill=dog_name),
    alpha = .3, point_alpha = 0.7, jittered_points = TRUE
  ) +labs(title = "The distribution of weights for each dog",
    x = "weight_lbs",
    y = "count")

dog_df1= dog_data%>%
  mutate(date=as.Date(with(dog_data,paste(year,month,day,sep="-"),"%Y-%m-%d")))%>%
  select(-year,-month,-day)

plot2=
                                        
  


```